platform:ios,'8.0'
target ‘ZucheDemo’ do
    pod 'AFNetworking', '~>3.1.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'AMapNavi’,‘2.3.0’ #导航SDK
    pod 'AMapSearch’, ‘~>4.4.1’
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
    pod ‘AMapFoundation’, ‘~>1.3.2’
    pod 'FMDB'
    pod 'AMapLocation', '~> 2.3.0'
end